### PR TITLE
Remove the #_top anchor for the first element

### PR DESCRIPTION
**Pull request by albandewilde**
may the first element in the list isn't at the top of the page, so I
change that to match to the element anchor

### CODE REVIEW

**Comment by dsagal** [comment]
The change is sensible, but the behavior with #_top is intentional -- there is no other link that scrolls back to the top, and the first heading is often a suitable choice for it. It's not a perfect behavior, but changing it would be a regression for some cases.

Perhaps this choice could be made somehow a property of the first link?

You can also override the theme just for your site using `custom_dir` (see https://www.mkdocs.org/user-guide/configuration/#theme).

**Comment by albandewilde** [comment]
I understand, but isn't that a duplicated feature (scrolling back to top) ? Because on keyboards there already is a key to do that, it's the [home key](https://en.wikipedia.org/wiki/Home_key "Home key").

Otherwise, it may can be an option which can be configured in the `mkdocs.yml` file ?

**Comment by dsagal** [comment]
Yeah, an option would be good.

**Comment by albandewilde** [comment]
I'm closing this PR because it was opened long time ago and it may be obsolete now.

**Pull request closed without merging**
